<a href="https://colab.research.google.com/github/Nikhithanicky/Testproject/blob/master/NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import nltk
import re
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
para = '''"Beans. I was trying to explain to somebody as we were flying in, that’s corn."
"That’s beans. And they were very impressed at my agricultural knowledge."
"Please give it up for Amaury once again for that outstanding introduction."
"I have a bunch of good friends here today, including somebody who I served with, who is one of the finest senators in the country, and we’re lucky to have him, your Senator, Dick Durbin is here.""'''
lem = WordNetLemmatizer()
sent = nltk.sent_tokenize(para)
corpus = []
for i in range(len(sent)):
    rev = re.sub('[^a-zA-Z]', ' ', sent[i])
    rev = rev.lower()
    rev = rev.split()
    rev = [lem.lemmatize(word) for word in rev if word not in set(stopwords.words('english'))]
    rev = ' '.join(rev)
    corpus.append(rev)
from sklearn.feature_extraction.text import TfidfVectorizer
tf=TfidfVectorizer()
r=tf.fit_transform(corpus).toarray()
print(r)

[[0.         0.         1.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.        ]
 [0.         0.         0.         0.         0.46262479 0.
  0.         0.         0.46262479 0.         0.46262479 0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.37935895 0.         0.46262479]
 [0.         0.         1.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.        ]
 [0.57735027 0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.57735027 0.         0.    

Text frequency inverse document frequency

BagOfWords

In [22]:
import nltk
import re
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
para = '''"Beans. I was trying to explain to somebody as we were flying in, that’s corn."
"That’s beans. And they were very impressed at my agricultural knowledge."
"Please give it up for Amaury once again for that outstanding introduction."
"I have a bunch of good friends here today, including somebody who I served with, who is one of the finest senators in the country, and we’re lucky to have him, your Senator, Dick Durbin is here.""'''
lem = WordNetLemmatizer()
sent = nltk.sent_tokenize(para)
corpus = []
for i in range(len(sent)):
    rev = re.sub('[^a-zA-Z]', ' ', sent[i])
    rev = rev.lower()
    rev = rev.split()
    rev = [lem.lemmatize(word) for word in rev if word not in set(stopwords.words('english'))]
    rev = ' '.join(rev)
    corpus.append(rev)
from sklearn.feature_extraction.text import CountVectorizer
tf=CountVectorizer()
r=tf.fit_transform(corpus).toarray()
print(r)

[[0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 1 0 0 0 0 0]
 [0 0 0 1 0 1 1 1 0 1 0 1 0 1 0 1 0 0 1 1 0 0 2 1 1 1 0]]
